### ISSUE TITLE
Clients fail to connect due to listen backlog of 4

### ISSUE THREAD

**Issue by redlicha** [openvstorage/accelio#1]
https://github.com/openvstorage/volumedriver/issues/184

Accelio's backlog was set to "4" to support iWARP in kernel mode: https://github.com/accelio/accelio/commit/0266a035d4184bd79a7bd46bbfa32639a545c094
Further investigation shows that previously the iWARP CM interpreted a backlog of '0' as no backlog. Semantics have changed however and now the iwcm interprets a backlog of "0" as "use default value" (256):
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=2f0304d21867476394cd51a54e97f7273d112261
```
~/Projects/linux/git$ git tag --contains 2f0304d21867476394cd51a54e97f7273d112261 | head
v3.17
v3.17-rc1
v3.17-rc2
v3.17-rc3
v3.17-rc4
v3.17-rc5
v3.17-rc6
v3.17-rc7
v3.18
v3.18-rc1
```

**Comment by redlicha** [comment]
Addressed by 9f0f7268f9feb0269990b93114ea68941ccaf041

**Comment by wimpers** [comment]
@redlicha this one can be set to state_verification?

**Comment by redlicha** [comment]
Correct

**Comment by pploegaert** [comment]
VALIDATED OK in autotest:
https://github.com/openvstorage/volumedriver/blob/dev/src/filesystem/test/NetworkServerTest.cpp#L1837
